"$schema" = 'https://starship.rs/config-schema.json'

format = "$username$hostname$directory$git_branch$git_state$git_status$cmd_duration$python$character"

[directory]
style = "#83a598"

[character]
success_symbol = "[❯](#d3869b)"
error_symbol = "[❯](#fb4934)"
vimcmd_symbol = "[❮](#b8bb26)"

[git_branch]
format = "[$branch]($style)"
style = "#928374"

[git_status]
format = "[($conflicted$untracked$modified$staged$renamed$deleted)]($style)"
style = "#fe8019"
conflicted = "="
untracked = "?"
modified = "!"
staged = "+"
renamed = "»"
deleted = "x"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#928374"

[cmd_duration]
format = "[$duration]($style) "
style = "#fabd2f"

[python]
format = "[$virtualenv]($style) "
style = "#928374"
detect_extensions = []
detect_files = []
